# Training Configuration for Wall-X Robotic Multi-Modal Learning
# This configuration supports multi-modal learning with vision, language, and action data
# Model and paths configuration
log_name: "robotic_training"
log_project: "vla_training"
model_type: wall-oss
pretrained_wallx_path: "/mnt/nas_ssd/workspace/wenboli/projects/Wall-X/wallx/models/wallx/wall-oss-flow"  # Must set
save_path: "/mnt/nas_ssd/workspace/wenboli/projects/Wall-X/output_models/26310_flow_act"                # Must set
use_fast_tokenizer: False                       # True: train FAST, False: train Flow
action_tokenizer_path: "/mnt/nas_ssd/workspace/wenboli/projects/Wall-X/fast"         # Must set if use_fast_tokenizer is true
processor_path: "/mnt/nas_ssd/workspace/wenboli/projects/Wall-X/wallx/models/wallx/wall-oss-flow"

freeze_vlm: false
use_selective_recompute: true

# Torch Profile
profile: False
profile_save_path: /path/to/profile/
profile_wait_iters: 10
profile_warmup_iters: 5
profile_active_iters: 2

# Training hyperparameters
num_warmup_steps: 100
num_training_steps: 64000000
learning_rate: 0.00005
min_lr: 0.00005
num_epoch: 10
gradient_accumulation_steps: 32
# batch_size_per_gpu: 
batch_size_per_gpu: 4
padding_side: left
epoch_save_interval: 5

# Training optimization settings 关闭即时编译
FSDP2: True
torch_compile: False

# 用于对齐连接 computes_norms.py 的产物（里面的字段要与下面相同），以正确初始化内部 Normalizer 的json读取 在 Normalizer 进行的多维度散装拼接成整体；由于ActionProcessor涉及到载入模型参数，内部逻辑是读取这里sum,这里我在相应文件处硬编码为20以适配，因此也就不再需要指定到20维度以加载预训练模型
dof_config:
  observation.ts.actions_joint_robot_position: 17
  observation.ts.actions_joint_gripper_position: 2
  # dummy_joint: 1

agent_pos_config:
  observation.ts.observations_joint_robot_position: 17
  observation.ts.observations_joint_gripper_position: 2
  # dummy_joint: 1

# # Checkpoint resuming configuration
# resume:
#   ckpt: "/path/to/resume_model/"
#   load_ckpt_only: true

norm_stats_path: "/mnt/nas_ssd/workspace/wenboli/projects/Wall-X/norm_stats/all_robots_action_stats.json"

# 新版本这个似乎不是很需要了
enable_customized_robot_config: true
customized_robot_config:
  name: "g1custom"
  customized_dof_config:
    "action_joint_robot_position": 17
    "action_joint_gripper_position": 2
    # "dummy_joint": 1
  customized_agent_pos_config:
    "state_joint_robot_position": 17
    "state_joint_gripper_position": 2
    # "dummy_joint": 1

# Data configuration
data:
  use_lerobot: true
  vqa_types: ["spatial"]

  # 用于 darw 测试 action
  generate_vqa_ratio: 0   # 有就一定走
  generate_cot_ratio: 0
  generate_subtask_ratio: 0


  # generate_vqa_ratio: 0.25   # 有就一定走
  # generate_cot_ratio: 0.33
  # generate_subtask_ratio: 0.5
  if_vqa: 0               # 1: VQA-only; missing VQA will be skipped
  path_drop_full_ratio: 0.5

  lerobot_config:
    repo_id: "g1custom"
    root: /mnt/nas_ssd/workspace/wenboli/projects/Wall-X/wallx/data/g1_new/lerobot/Teleop_251103_Sort_Anonymous_10Hz_refactorized
    episodes: null
    image_transforms: null
    delta_timestamps: null
    tolerance_s: 1e-4
    revision: null
    force_cache_sync: false
    download_videos: false
    video_backend: pyav
    modality_json: "/mnt/nas_ssd/workspace/wenboli/projects/Wall-X/wallx/data/g1_new/lerobot/Teleop_251103_Sort_Anonymous_10Hz_refactorized/meta/modality.json"

    

  action_horizon: 32
  train_test_split: 0.95

  # Action keys for observation and prediction 用于构造 PreprocessedDataset 使用
  obs_action_keys:
    - state_joint_robot_position
    - state_joint_gripper_position

  predict_action_keys:
    - action_joint_robot_position
    - action_joint_gripper_position


  # Image resolution configuration for different camera views
  resolution:
    face_view: 256
    left_wrist_view: 256
    right_wrist_view: 256
